' -------- CORRECT Line14 --------
' Compute L14 dynamically to match Line15â€™s end
y15_end = y11_start - L15
y14_start = y13_start
L14 = y14_start - y15_end
y14_end = y15_end

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x14) & "mil", "Y:=", CStr(y14_start) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x14) & "mil", "Y:=", CStr(y14_end) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line14", "Flags:=", "", "Color:=", "(0 255 0)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)
