' Dimensions
Dim Wio, L1, L2, L3, L4
Wio = 7.5
L1 = 25.0
L2 = 15.0
L3 = 8.0
L4 = 12.0

Dim material, transparency
material = Chr(34) & "copper" & Chr(34)
transparency = 0

' -------- Segment: Wio (vertical up from origin) --------
Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", "0mil", "Y:=", "0mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", "0mil", "Y:=", CStr(Wio) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Wio", "Flags:=", "", "Color:=", "(255 0 0)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

' -------- Segment: Line1 (horizontal right from Wio top) --------
Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", "0mil", "Y:=", CStr(Wio) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(L1) & "mil", "Y:=", CStr(Wio) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line1", "Flags:=", "", "Color:=", "(0 255 0)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

' -------- Segment: Line2 (horizontal right from Wio base) --------
Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", "0mil", "Y:=", "0mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(L1) & "mil", "Y:=", "0mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line2", "Flags:=", "", "Color:=", "(0 0 255)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

' -------- Segment: Line4 (diagonal up-right from Line1 end) --------
Dim x4, y4
x4 = L1 + L4 * 0.707
y4 = Wio + L4 * 0.707

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(L1) & "mil", "Y:=", CStr(Wio) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x4) & "mil", "Y:=", CStr(y4) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line4", "Flags:=", "", "Color:=", "(255 128 0)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

' -------- Segment: Line3 (diagonal up-right from Line2 end) --------
Dim x3, y3
x3 = L1 + L3 * 0.707
y3 = L3 * 0.707

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(L1) & "mil", "Y:=", "0mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x3) & "mil", "Y:=", CStr(y3) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line3", "Flags:=", "", "Color:=", "(255 0 255)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)





' Updated dimensions
Wio = 7.0
L1 = 50
L2 = 51
L3 = 26.28
L4 = 20.48
L5 = 103.36
L6 = 106.26

Dim x3, y3, x4, y4
x3 = L1 + L3 * 0.707
y3 = L3 * 0.707
x4 = L1 + L4 * 0.707
y4 = Wio + L4 * 0.707

' -------- Segment: Line5 (vertical up from Line3 end) --------
Dim y5
y5 = y3 + L5

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x3) & "mil", "Y:=", CStr(y3) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x3) & "mil", "Y:=", CStr(y5) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line5", "Flags:=", "", "Color:=", "(255 255 0)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

' -------- Segment: Line6 (vertical up from Line4 end) --------
Dim y6
y6 = y4 + L6

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x4) & "mil", "Y:=", CStr(y4) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x4) & "mil", "Y:=", CStr(y6) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line6", "Flags:=", "", "Color:=", "(0 255 255)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)





' Add line7 and line8 (angled)
Dim L7
L7 = 14.3378

Dim x7_start, y7_start, x7_end, y7_end
x7_start = x4
y7_start = y6
x7_end = x7_start - L7 * 0.7071
y7_end = y7_start + L7 * 0.7071

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x7_start) & "mil", "Y:=", CStr(y7_start) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x7_end) & "mil", "Y:=", CStr(y7_end) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line7", "Flags:=", "", "Color:=", "(255 200 0)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

Dim x8_start, y8_start, x8_end, y8_end
x8_start = x3
y8_start = y5
x8_end = x8_start + L7 * 0.7071
y8_end = y8_start + L7 * 0.7071

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x8_start) & "mil", "Y:=", CStr(y8_start) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x8_end) & "mil", "Y:=", CStr(y8_end) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line8", "Flags:=", "", "Color:=", "(0 255 128)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)



' -------- Segment: Line10 (vertical up from Line7 end) --------
Dim L10, x10, y10_start, y10_end
L10 = 8.58
x10 = x7_end
y10_start = y7_end
y10_end = y10_start + L10

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x10) & "mil", "Y:=", CStr(y10_start) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x10) & "mil", "Y:=", CStr(y10_end) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line10", "Flags:=", "", "Color:=", "(128 128 255)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)

' -------- Segment: Line9 (vertical up from Line8 end) --------
Dim L9, x9, y9_start, y9_end
L9 = 2.65
x9 = x8_end
y9_start = y8_end
y9_end = y9_start + L9

Call oEditor.CreatePolyline( _
  Array("NAME:PolylineParameters", _
    "IsPolylineCovered:=", true, "IsPolylineClosed:=", false, _
    Array("NAME:PolylinePoints", _
      Array("NAME:PLPoint", "X:=", CStr(x9) & "mil", "Y:=", CStr(y9_start) & "mil", "Z:=", "0mil"), _
      Array("NAME:PLPoint", "X:=", CStr(x9) & "mil", "Y:=", CStr(y9_end) & "mil", "Z:=", "0mil") _
    ), _
    Array("NAME:PolylineSegments", Array("NAME:PLSegment", "SegmentType:=", "Line", "StartIndex:=", 0, "NoOfPoints:=", 2)), _
    Array("NAME:PolylineXSection", "XSectionType:=", "None", "XSectionOrient:=", "Auto", "XSectionWidth:=", "0mil", _
      "XSectionTopWidth:=", "0mil", "XSectionHeight:=", "0mil", "XSectionNumSegments:=", "0", "XSectionBendType:=", "Corner") _
  ), _
  Array("NAME:Attributes", "Name:=", "Seg_Line9", "Flags:=", "", "Color:=", "(0 128 255)", _
    "Transparency:=", transparency, "PartCoordinateSystem:=", "Global", "MaterialValue:=", material, "SolveInside:=", false) _
)
